#!/usr/bin/env bash

SPECFILE="transgui.spec"

set -e

#  Get the full path to the spec file
SPECFILE=$(dirname "$(realpath "$0")")/$SPECFILE

#  Parse the package name, version and release out of the spec file
NAME=$(sed -n 's/^Name:[[:space:]]*//p' "$SPECFILE")
VERSION=$(sed -n 's/^Version:[[:space:]]*//p' "$SPECFILE")
RELEASE=$(sed -n 's/^Release:[[:space:]]*//;s/%{?dist}//p' "$SPECFILE")

if [ $(cat /etc/hostname) == "fang.localdomain" ]; then
        echo "Building $NAME in fedora-rpmbuild:30 container ..."
        podman run --interactive --name=rpmbuild --rm --tty --volume=${HOME}:${HOME} localhost/fedora-rpmbuild:30 "$(realpath "$0")"
        echo -e "\nBuilding $NAME in fedora-rpmbuild:31 container ..."
        podman run --interactive --name=rpmbuild --rm --tty --volume=${HOME}:${HOME} localhost/fedora-rpmbuild:31 "$(realpath "$0")"
	echo -e "\nTest installation of ${NAME}-${VERSION}-${RELEASE}.fc30.x86_64.rpm in fedora-rpmbuild:30 container ..."
	podman run --interactive --name=rpmbuild --rm --tty --volume=${HOME}:${HOME} localhost/fedora-rpmbuild:30 dnf install -y ${HOME}/rpmbuild/RPMS/x86_64/${NAME}-${VERSION}-${RELEASE}.fc30.x86_64.rpm

	echo -e "\nTest installation of ${NAME}-${VERSION}-${RELEASE}.fc31.x86_64.rpm in fedora-rpmbuild:31 container ..."
	podman run --interactive --name=rpmbuild --rm --tty --volume=${HOME}:${HOME} localhost/fedora-rpmbuild:31 dnf install -y ${HOME}/rpmbuild/RPMS/x86_64/${NAME}-${VERSION}-${RELEASE}.fc31.x86_64.rpm
else
        echo -e "\nUpdate system software ..."
        dnf -y upgrade
	dnf -y install wget lazarus fpc openssl-devel

	#  Get the source file
	wget -O "${HOME}/rpmbuild/SOURCES/${NAME}-${VERSION}.tar.gz" "https://github.com/transmission-remote-gui/transgui/archive/v5.18.0.tar.gz"

	#  Build the packages.  Try twice, in case of an Access Exception, which happens occasionally
	if ! rpmbuild -ba "$SPECFILE"; then
		echo -e "\nrpmbuild failed, retrying rpmbuild ..."
		rpmbuild -ba "$SPECFILE"
	fi

	echo -e "\nCopying RPM files to host system ..."
	mv ${HOME}/rpmbuild/RPMS/x86_64/${NAME}-${VERSION}-${RELEASE}.*.x86_64.rpm /home/dlk/rpmbuild/RPMS/x86_64/
	mv ${HOME}/rpmbuild/SRPMS/${NAME}-${VERSION}-${RELEASE}.*.src.rpm /home/dlk/rpmbuild/SRPMS/
fi
